foreground   #dec3c4
background   #0E0D0F
cursor       #dec3c4

color0       #0E0D0F
color8       #9b8889
color1       #9B5F6C
color9       #9B5F6C
color2       #686E88
color10      #686E88
color3       #A27689
color11      #A27689
color4       #C37C85
color12      #C37C85
color5       #AE8883
color13      #AE8883
color6       #AD8C9F
color14      #AD8C9F
color7       #dec3c4
color15      #dec3c4
