wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpapers/aishot-1639.jpg
    fit_mode = cover
}
wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/cherry_lop_left2.png
    fit_mode = cover
}

splash = false
