wallpaper {
    monitor = DP-1
    path = ~/Pictures/wallpapers/output/neon_sunset_bottom.png
    fit_mode = tile
}
wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/output/neon_sunset_top.png
    fit_mode = tile
}

splash = false
