
[ids]
*

[main]
# leave normal typing alone

[altgr]
p  = G-8 # altgr + p : [
leftbrace = G-9 # altgr + å : ]
semicolon  = G-7 # altgr + ö : {
apostrophe = G-0 # altgr + ä : }
dot   = S-8 # altgr + . : (
slash = S-9 # altgr + - : )

[main]
capslock = overload(nav, esc) #tap caps : escape, hold : nav

[nav]
a = left
s = down
w = up
d = right
k = left
l = down
o = up
semicolon = right